require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/AccessorGrouping:
  Enabled: false
Style/DateTime:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/RescueModifier:
  Exclude:
    - "spec/**/*"
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: "comma"
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: "comma"
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: "comma"
Style/ReturnNil:
  Enabled: true
