inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-sorbet
  - './cops/attribute_placement'

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "**/templates/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "lib/tasks/*"
    - "**/Rakefile"
    - "bin/**/*"
    - "config/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "docs/**/*"
    - "node_modules/**/*"
    - "Guardfile"
    - ".githooks"
    - ".rubocop.yml"
Metrics/ClassLength:
  Enabled: false
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Metrics/ModuleLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Metrics/AbcSize:
  Max: 30
  Enabled: false
  Exclude:
    - "db/**/*"
Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"
    - "app/admin/**/*"
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/**/*"
    - spec/mailers/previews/**/*
Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\s*#', '^\s*/.*/,?$']
Metrics/ParameterLists:
  Enabled: false
Performance/RedundantBlockCall:
  Enabled: false
RSpec/AnyInstance:
  Exclude:
    - "spec/features/**/*"
RSpec/Capybara/FeatureMethods:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  CustomTransform:
    AfterShip: aftership
    IdPEntitiesController: idp_entities_controller
    IdPEntity: idp_entity
    IdPEntityIdReader: idp_entity_id_reader
    IdPEntityPolicy: idp_entity_policy
    IdPEntityService: idp_entity_service
    IdPSettingsAdapter: idp_settings_adapter
    OAuth: oauth
    OAuth2: oauth2
    OAuth2Service: oauth2_service
    OmniAuthEloqua: omniauth_eloqua
    RetrieveOrganizationIdPEntity: retrieve_organization_idp_entity
    UpdateOrganizationIdPEntity: update_organization_idp_entity
    UpsertIdPEntityFromMetadata: upsert_idp_entity_from_metadata
RSpec/MultipleExpectations:
  Exclude:
    - "spec/features/**/*"
    - "spec/integration/**/*"
RSpec/NestedGroups:
  Max: 10
RSpec/RepeatedExample:
  Exclude:
    - "spec/policies/**/*"
# The following doesn't allow `.constantize`
Sorbet/ConstantsFromStrings:
  Enabled: false
# The following doesn't allow eg. `ActiveRecord::Migration[5.2]`
Sorbet/ForbidSuperclassConstLiteral:
  Exclude:
    - 'db/migrate/**/*'
Sorbet/ValidSigil:
  MinimumStrictness: 'ignore'
Sorbet/FalseSigil:
  Enabled: true
  Exclude:
    - 'gems/**/*'
Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "app/**/*"
  Exclude:
    - "app/admin/**/*"
    - "app/lib/chunked/middleware.rb"
    - "app/services/template_service/email_router.rb"
Style/AccessorGrouping:
  Enabled: false
Style/DateTime:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/RescueModifier:
  Exclude:
    - "spec/**/*"
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: "comma"
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: "comma"
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: "comma"
Style/ReturnNil:
  Enabled: true

# Rails Cops
Rails/ApplicationController:
  Exclude:
    - 'app/controllers/admin/oauth2/callbacks_controller.rb'
    - 'app/controllers/api/v2/external_api_controller.rb'
    - 'app/controllers/errors_controller.rb'
    - 'app/controllers/health_controller.rb'
    - 'app/controllers/vendor_platform/vendor_platform_controller.rb'
    - 'app/controllers/webhooks/webhook_controller.rb'
Rails/BulkChangeTable:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20181109031532_create_engage.rb'
Rails/Delegate:
  EnforceForPrefixed: false
  Exclude:
    - 'app/lib/recaptcha_manager/middleware.rb'
Rails/DynamicFindBy:
  Enabled: false
Rails/FindById:
  Enabled: false
Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/2018*.rb'
    - 'db/migrate/2019*.rb'
    - 'db/migrate/2020*.rb'
Rails/SkipsModelValidations:
  AllowedMethods:
    - 'touch'
    - 'touch_all'

# temporary disabled
Lint/ToJSON:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/RepeatedExampleGroupBody:
  Enabled: false
RSpec/RepeatedExampleGroupDescription:
  Enabled: false

# New cops upgrade from 0.84.0 to 1.14.0, needs to be reviewed
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
Lint/UselessMethodDefinition:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/StringConcatenation:
  Enabled: false

# New cops upgrade from rubocop-rspec from 1.39.0 to 2.0.1, needs to be reviewed
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# New cops upgrade from rubocop-rails from 2.6.0 to 2.9.1, needs to be reviewed
Rails/Pluck:
  Enabled: false
Rails/SquishedSQLHeredocs:
  Enabled: false

# New cops upgrade from rubocop-performance from 1.10.2 to 1.13.3
Performance/BigDecimalWithNumericArgument:
  Exclude:
    - 'spec/**/*.rb'
